# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import im2txt_pb2 as im2txt__pb2


class Im2TxtStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/Im2Txt/Run',
        request_serializer=im2txt__pb2.Im2TxtRequest.SerializeToString,
        response_deserializer=im2txt__pb2.Im2TxtReply.FromString,
        )


class Im2TxtServicer(object):
  """The greeting service definition.
  """

  def Run(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Im2TxtServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=im2txt__pb2.Im2TxtRequest.FromString,
          response_serializer=im2txt__pb2.Im2TxtReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Im2Txt', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
