# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: im2txt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='im2txt.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cim2txt.proto\"\x1e\n\rIm2TxtRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1b\n\x0bIm2TxtReply\x12\x0c\n\x04text\x18\x01 \x01(\t2/\n\x06Im2Txt\x12%\n\x03Run\x12\x0e.Im2TxtRequest\x1a\x0c.Im2TxtReply\"\x00\x62\x06proto3')
)




_IM2TXTREQUEST = _descriptor.Descriptor(
  name='Im2TxtRequest',
  full_name='Im2TxtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='Im2TxtRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=46,
)


_IM2TXTREPLY = _descriptor.Descriptor(
  name='Im2TxtReply',
  full_name='Im2TxtReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Im2TxtReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Im2TxtRequest'] = _IM2TXTREQUEST
DESCRIPTOR.message_types_by_name['Im2TxtReply'] = _IM2TXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Im2TxtRequest = _reflection.GeneratedProtocolMessageType('Im2TxtRequest', (_message.Message,), dict(
  DESCRIPTOR = _IM2TXTREQUEST,
  __module__ = 'im2txt_pb2'
  # @@protoc_insertion_point(class_scope:Im2TxtRequest)
  ))
_sym_db.RegisterMessage(Im2TxtRequest)

Im2TxtReply = _reflection.GeneratedProtocolMessageType('Im2TxtReply', (_message.Message,), dict(
  DESCRIPTOR = _IM2TXTREPLY,
  __module__ = 'im2txt_pb2'
  # @@protoc_insertion_point(class_scope:Im2TxtReply)
  ))
_sym_db.RegisterMessage(Im2TxtReply)



_IM2TXT = _descriptor.ServiceDescriptor(
  name='Im2Txt',
  full_name='Im2Txt',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=77,
  serialized_end=124,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Im2Txt.Run',
    index=0,
    containing_service=None,
    input_type=_IM2TXTREQUEST,
    output_type=_IM2TXTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IM2TXT)

DESCRIPTOR.services_by_name['Im2Txt'] = _IM2TXT

# @@protoc_insertion_point(module_scope)
